name: 'CAF-Test'

on:
    push:
        branches:
            - main
        # paths:
        #     - 'environments/dev/**'    
env:
      ENV_NAME: dev

jobs:
    terraform:
        name: 'Terraform'
        runs-on: ubuntu-latest
        
        permissions:
            id-token: write
            contents: write

        steps:
 
            - name: Azure Login
              uses: azure/login@v1
              with:
                    client-id: ${{ secrets.ARM_CLIENT_ID }}
                    tenant-id: ${{ secrets.ARM_TENANT_ID }}
                    subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                    terraform_version: latest
                    
            - name: Terraform Version
              run: terraform --version
                

            - name: Terraform init
              run: terraform init
              working-directory: /home/runner/work/azure-infra/azure-infra/
            
            - name: Terraform validate
              run: terraform validate
              working-directory: /home/runner/work/azure-infra/azure-infra/
            
            - name: Terraform Plan
              run: terraform plan
              working-directory: /home/runner/work/azure-infra/azure-infra/

            - name: Terraform Apply
              run: terraform apply -auto-approve
              working-directory: /home/runner/work/azure-infra/azure-infra/