name: 'Terragrunt'

on:
    push:
        branches:
            - main

jobs:
    terragrunt:
        name: 'Terragrunt'
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: write

        steps:
 
            - name: Azure Login
              uses: azure/login@v1
              with:
                    client-id: ${{ secrets.ARM_CLIENT_ID }}
                    tenant-id: ${{ secrets.ARM_TENANT_ID }}
                    subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                    terraform_version: 1.7.5
               

            - name: Install Terragrunt
              run: |
                    TERRAGRUNT_VERSION=v0.55.16
                    curl -LOs https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
                    chmod +x terragrunt_linux_amd64
                    sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
              

            - name: Print GitHub repository
              run: echo $GITHUB_REPOSITORY

            - name: current the working directory
              run: pwd

            - name: List directory contents
              run: ls -la /home/runner/work

            - name: List repository contents
              run: ls -la /home/runner/work/azure-infra/azure-infra
  
            - name: Change working directory
              run: |
                cd /home/runner/work/azure-infra/azure-infra
                pwd  # This should now print /home/runner/work/azure-infra/azure-infra
            
            - name: current the working directory
              run: pwd
            

            - name: Terragrunt validate
              run: terragrunt validate
              working-directory: /home/runner/work/azure-infra/azure-infra/environments/dev/ 
            
            - name: Save state
              run: echo "{name}={value}" >> $GITHUB_STATE
              
            - name: Set output
              run: echo "{name}={value}" >> $GITHUB_OUTPUT

            - name: Terragrunt Plan
              run: terragrunt plan
              working-directory: /home/runner/work/azure-infra/azure-infra/environments/dev/

            - name: Terragrunt Apply
              run: terragrunt apply -auto-approve
              working-directory: /home/runner/work/azure-infra/azure-infra/environments/dev/